### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by alexbaretta** [esperco/atdj#3]
I'm experimenting with atdj. It seems to be in a state of relative disrepair. Is this indeed no longer maintained since 2015?

**Comment by alexbaretta** [comment]
Looks like I might have been looking in the wrong place:

https://github.com/mjambon/atd/tree/master/atdj/src

**Comment by mjambon** [comment]
Yes, atdj is now part of `atd`, along with atdgen. Sorry. I'll update the project description.

**Comment by mjambon** [comment]
The move is very recent. It makes maintenance easier, so even if there are no new features in atdj, it still builds and installs properly.
